# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior
  property :file_uuid, predicate: ::RDF::Vocab::DC11.identifier, multiple: false
  before_create :set_uuid
  delegate :original_checksum,
           :label,
           :date_created,
           :date_modified,
           :file_name,
           :file_size,
           :licence,
           :format_label,
           :mime_type,
           to: :original_file

  def set_uuid
    self.file_uuid = SecureRandom.uuid
  end
end
