# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  property :file_uuid, predicate: ::RDF::Vocab::DC11.identifier, multiple: false
  property :checksum_uuid, predicate: ::RDF::URI.new("http://lib.my.edu/checksum_uuid"), multiple: false
  include ::Hyrax::FileSetBehavior

  delegate :file_name,
           to: :original_file
  before_create :set_uuids

  def set_uuids
    self.file_uuid ||= SecureRandom.uuid
    self.checksum_uuid ||= SecureRandom.uuid
    true
  end
end
