source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.3'
gem 'pg', '~> 0.19.0'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'

gem 'hyrax', '2.1.0.beta1'
gem 'blacklight', '~> 6.14'
gem 'blacklight_advanced_search', '~> 6.0'
gem 'blackrat_yaml_config'
gem 'json-schema', '~> 2.8.0'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'debase'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubocop', '~> 0.49.1', require: false
  gem 'ruby-debug-ide'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara', '~> 2.13'
  gem 'factory_girl_rails', '~> 4.8.0'
  gem 'fcrepo_wrapper'
  gem 'pry-byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rails-controller-testing', '~> 1.0.2'
  gem 'rspec-rails'
  gem 'solr_wrapper', '>= 0.3'
  gem 'vcr', '~> 3.0.3'
  gem 'webmock', '~> 3.0.1'
  gem 'selenium-webdriver'
  gem 'wisper-rspec'
end

gem 'rsolr', '>= 1.0'
gem 'jquery-rails'
gem 'devise'
gem 'devise-guests', '~> 0.6'
gem 'hydra-role-management'
gem 'bootstrap-datepicker-rails'
gem 'aws-sdk', '>= 2.9.15'
gem 'tinymce-rails-imageupload', '4.0.17.beta.2' # we need this specific version to fix an asset compilation problem
# gem 'willow_sword', git: "https://github.com/cottagelabs/willow_sword.git", branch: "master"
gem 'wisper', '2.0.0'

gem 'riiif', '~> 1.1'
gem 'noid-rails'
