source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.3'
gem 'pg', '~> 0.19.0'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'

gem 'hyrax', github: 'cottagelabs/hyrax'

gem 'blacklight_advanced_search', '~> 6.0'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  # helps enforce good coding standards
  gem 'rubocop', '~> 0.49.1', require: false
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'solr_wrapper', '>= 0.3'
  gem 'fcrepo_wrapper'
  gem 'ruby-debug-ide'
  gem 'debase'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :test do
  gem 'rspec-rails'
  gem 'webmock', '~> 3.0.1'
  gem 'vcr', '~> 3.0.3'
  gem 'factory_girl_rails', '~> 4.8.0'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'json-schema', '~> 2.8.0'
  gem 'rails-controller-testing', '~> 1.0.2'
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

gem 'rsolr', '>= 1.0'
gem 'devise'
gem 'devise-guests', '~> 0.6'
gem 'hydra-role-management'
gem 'bootstrap-datepicker-rails'
gem 'aws-sdk', '>= 2.9.15'
gem 'tinymce-rails-imageupload', '4.0.17.beta.2' # we need this specific version to fix an asset compilation problem
# gem 'willow_sword', git: "https://github.com/cottagelabs/willow_sword.git", branch: "master"
